[tool.pytest.ini_options]
pythonpath = [
  "."
]

# todo: fix other tool tests and remove this filter
testpaths = [
    "tests/test_correlations.py",
    "tests/test_population_activity.py",
    "tests/test_peri_event_workflow.py",
]
